module.exports = {
  RECEIVE_ALL_MEMBERS: "RECEIVE_ALL_MEMBERS",
  RECEIVE_MEMBER: "RECEIVE_MEMBER",
  RECEIVE_CREATED_MEMBER: "RECEIVE_CREATED_MEMBER",
  RECEIVE_MEMBER_ERRORS: "RECEIVE_MEMBER_ERRORS"
};
